apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
#          - key: role
#            operator: In
#            values:
#            - storage-node
          - key: node-role.kubernetes.io/storage-node
            operator: Exists
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
