apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: kubeinvaders
      meta.helm.sh/release-namespace: kubeinvaders
    creationTimestamp: "2021-06-30T20:26:49Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: kubeinvaders
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeinvaders
      helm.sh/chart: kubeinvaders-1.4
    name: kubeinvaders
    namespace: kubeinvaders
    resourceVersion: "647482"
    uid: a5f5c6b9-bcea-490f-8b03-913aa4aaed2c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: kubeinvaders
        app.kubernetes.io/name: kubeinvaders
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: kubeinvaders
          app.kubernetes.io/name: kubeinvaders
      spec:
        containers:
        - env:
          - name: ENDPOINT
            value: kubeinvaders.local
          - name: ROUTE_HOST
            value: kubeinvaders.local
          - name: NAMESPACE
            value: mayastor, default
          image: luckysideburn/kubeinvaders:v1.4
          imagePullPolicy: Always
          name: kubeinvaders
          ports:
#          - containerPort: 8080
          - containerPort: 80
            name: http
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: kubeinvaders
        serviceAccountName: kubeinvaders
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-06-30T20:26:51Z"
      lastUpdateTime: "2021-06-30T20:26:51Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-06-30T20:26:49Z"
      lastUpdateTime: "2021-06-30T20:26:51Z"
      message: ReplicaSet "kubeinvaders-d6bdbd68c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
